[1,"==> quarto preview adv_visualization.qmd --to html --no-watch-inputs --no-browse\n\n"]
[1,"ERROR: An unexpected network error occurred. (os error 59): stat 'adv_visualization.qmd'\n\nStack trace:\n    at Object.statSync (ext:deno_fs/30_fs.js:363:7)\n    at existsSync (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:495:27)\n    at Command.fn (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:97990:10)\n    at async Command.execute (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:8104:13)\n    at async quarto (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:115004:5)\n    at async file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:115022:9\n"]
